import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Box, Typography } from "@mui/material";
import dynamic from 'next/dynamic';
const inter = Inter({ subsets: ['latin'] })


const Animation = dynamic(
  () => import('../src/components/common/lottie'),
  { loading: () => <p>Loading ...</p>, ssr: true }
)

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>
      <Box sx={{
                    padding: '10em',
                    display: 'grid',
      }}>
        
        <Animation icon={'rocket'}/> 
        <Animation icon={'figma'}/> 
        <Animation icon={'calculator'}/> 
        </Box>
      <h1>front end</h1>
    </>
  )
}
