import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Box, Typography } from "@mui/material";
import { Player } from '@lottiefiles/react-lottie-player';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      
      </Head>
      <Box sx={{
                    padding: '10em',
                    
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
      }}>
        
              
      <Player
  autoplay
  loop
  src="rocket.json"
  style={{ height: '300px', width: '300px' }}
>
  {/* <Controls visible={true} buttons={['play', 'repeat', 'frame', 'debug']} /> */}
      </Player>
      <Player
  autoplay
  loop
  src="figma.json"
  style={{ height: '300px', width: '300px' }}
>
  {/* <Controls visible={true} buttons={['play', 'repeat', 'frame', 'debug']} /> */}
      </Player>
      <Player
  autoplay
  loop
  src="calculator.json"
  style={{ height: '300px', width: '300px' }}
>
  {/* <Controls visible={true} buttons={['play', 'repeat', 'frame', 'debug']} /> */}
        </Player>
        </Box>
      <h1>front end</h1>
    </>
  )
}
